class homeBanner {
    elements = {
        forexTxt: () => cy.findByRole('navigation').findByRole('link', { name: 'Forex' }),
        cryptoTxt: () => cy.findByRole('navigation').findByRole('link', { name: 'Cryptocurrencies' }),
        stockIndicesTxt: () => cy.findByRole('navigation').findByRole('link', { name: 'Stocks & indices' }),
        commoditiesTxt: () => cy.findByRole('navigation').findByRole('link', { name: 'Commodities' }),
        derivedIndicesTxt: () => cy.findByRole('navigation').findByRole('link', { name: 'Derived indices' }),
        bannerForexTxt: () => cy.findByTestId('typewriter-wrapper').contains('Forex'),
        bannerCryptoTxt: () => cy.findByTestId('typewriter-wrapper').contains('Cryptocurrencies'),
        bannerStockIndicesTxt: () => cy.findByTestId('typewriter-wrapper').contains('Stocks & indices'),
        bannerCommoditiesTxt: () => cy.findByTestId('typewriter-wrapper').contains('Commodities'),
        bannerDerivedIndicesTxt: () => cy.findByTestId('typewriter-wrapper').contains('Derived Indices'),


        createFreeDemoAccount: () => cy.findByLabelText('create free demo account'),
        hamBurgerMenu: () => cy.get('[data-cy="mobile-header"]').find('[data-cy="hamburger-menu"]'),
        derivLogo: () =>   cy.get('[data-cy="mobile-header"]').find('[data-cy="deriv-logo"]'),
        langEnglish: () => cy.findByText('English'),
        tradeMenu: () => cy.findByRole('navigation').contains('Trade'),
        marketsMenu: () => cy.findByRole('navigation').contains('Markets'),
        aboutUsMenu: () => cy.findByRole('navigation').contains('About us'),
        resourcesMenu: () => cy.findByRole('navigation').contains('Resources'),
        legalMenu: () => cy.findByRole('navigation').contains('Legal'),
        partnersMenu: () => cy.findByRole('navigation').contains('Partners'),
        backIcon: () => cy.get('[data-cy="nav-back-icon"]'),
        crossIcon: () => cy.get('[data-cy="nav-cross-icon"]'),
        cfdMenu: () => cy.findAllByRole('link', { name: 'CFDs' }),
        cfdHeading: () => cy.findAllByRole('heading', { name: 'CFD trading' }),
        optionsMenu: () => cy.findAllByRole('link', { name: 'Options' }),
        multiplierMenu: () => cy.findAllByRole('link', { name: 'Multipliers' }),
        mt5Link: () => cy.findAllByRole('link', { name: 'Deriv MT5' }),
        dtraderLink: () => cy.findAllByRole('link', { name: 'Deriv Trader' }),
        derivxLink: () => cy.findAllByRole('link', { name: 'Deriv X' }),
        smartTraderLink: () => cy.findAllByRole('link', { name: 'SmartTrader' }),
        BinaryBotLink: () => cy.findAllByRole('link', { name: 'Binary Bot' }),
        cTraderLink: () => cy.findAllByRole('link', { name: 'Deriv cTrader' }),
        derivGo: () => cy.findAllByRole('link', { name: 'Deriv GO' }),
        derivBot: () => cy.findAllByRole('link', { name: 'Deriv Bot' }),
        etfLink: () => cy.findByRole('link', { name: 'Exchange-traded funds (ETFs)' }),
        derivPrime: () => cy.findAllByRole('link', { name: 'Deriv Prime' }),
        affiliatesIbs: () => cy.findAllByRole('link', { name: 'Affiliates and IBs' }),
        paymentAgent: () => cy.findAllByRole('link', { name: 'Payment agents' }),
        apiLink: () => cy.findAllByRole('link', { name: 'API' }),
        affiliates: () => cy.findAllByRole('link', { name: 'Affiliates' }),
        whoWeAre: () => cy.findAllByRole('link', { name: 'Who we are' }),
        whyChooseUs: () => cy.findAllByRole('link', { name: 'Why choose us' }),
        partnershipProgrammes: () => cy.findAllByRole('link', { name: 'Partnership programmes' }),
        contactUs: () => cy.findAllByRole('link', { name: 'Contact us' }),
        careers: () => cy.findAllByRole('link', { name: 'Careers' }),
        derivLife: () => cy.findAllByRole('link', { name: 'Deriv Life' }),
        helpCentre: () => cy.findAllByRole('link', { name: 'Help centre' }),
        community: () => cy.findAllByRole('link', { name: 'Community' }),
        traderstool: () => cy.findAllByRole('link', { name: 'Traders\' tools' }),
        paymentMethod: () => cy.findAllByRole('link', { name: 'Payment methods' }),
        derivMt5: () => cy.findAllByRole('link', { name: 'Deriv MT5 signals' }),
        statusPage: () => cy.findAllByRole('link', { name: 'Status page' }),
        derivBlog: () => cy.findAllByRole('link', { name: 'Deriv Blog' }),
        regulatoryInfo: () => cy.findAllByRole('link', { name: 'Regulatory information' }),
        termsCondition: () => cy.findAllByRole('link', { name: 'Terms & conditions' }),
        secureResponsible: () => cy.findAllByRole('link', { name: 'Secure & responsible trading' }),
        cfdFloatingText: () => cy.contains('% of retail investor accounts lose money when trading CFDs with Deriv, read our full Risk disclosure here.')
    }

}

module.exports = new homeBanner();