name: APITEST
on:
  push:
    branches: ["master"]
jobs:
  run-e2e-smoketests:
    runs-on: ubuntu-latest
    name: Results
    steps:
     - name: Trigger E2E Test Repo
       run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        "https://api.github.com/repos/deriv-com/e2e-deriv-com/dispatches" \
        -d '{
           "event_type": "run-e2e-tests",
           "client_payload": {
            "url": "https://staging.deriv.com/",
            "PR": "${{ github.event.pull_request }}"
           }
          }'
