name: Webflow Percy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Select the environment
        default: https://webflow.deriv.com
      suite:
        type: choice
        description: Run full or rerun
        options:
        - full
        - rerun(not in use)
      commit_message:
        type: string
        description: Commit message
        required: true
        default: 'Manual Percy run'
      percy_build_number:
        type: string
        description: 'Percy build number'
        

jobs:
  percy-run:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false # https://github.com/cypress-io/github-action/issues/48

    steps:
    - name: Checkout external repository with Cypress tests
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        repository: deriv-com/e2e-deriv-com # Replace with your repository name
    - name: Install percy cli
      run: |
          npm i @percy/cli@1.27.3
          echo "Installed Percy CLI version: $(npx percy --version)"
    - name: Install percy cypress
      run: |
          npm install --save-dev @percy/cypress
          npm install cypress --save-dev
          echo "Percy Cypress version: $(npx percy --version)"
          echo "Cypress version: $(npx cypress --version)" 
          echo "commit message is ${{ github.event.inputs.commit_message }}"
    - name: Run Percy  
      if: ${{ github.event.inputs.suite == 'full' && github.event.inputs.rerun == '' }}
      # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
      uses: cypress-io/github-action@1b70233146622b69e789ccdd4f9452adc638d25a
      with:
        record: true
        parallel: true # Runs test in parallel using settings above
        spec: cypress/e2e/webflow/Percy/allPagesSnapshot.cy.js
        command: npx percy exec -- cypress run --spec cypress/e2e/webflow/Percy/percy.cy.js
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TEST_TOKEN }}
        PERCY_COMMIT: ${{ github.event.inputs.commit_message }}
        TEST_SUITE: ${{ github.event.inputs.suite }}
        WEBFLOW_ENV: ${{ github.event.inputs.environment }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_WEBFLOW_RECORD_KEY }}
        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_WEBFLOW_PROJECT_ID }}
        # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Set Base Url from client_payload.
        CYPRESS_BASE_URL: "${{ github.event.inputs.environment }}"
        # Send PR details to Cypress test run
        COMMIT_INFO_MESSAGE: Manual Run of "${{ github.event.inputs.suite }} tests" on "${{ github.event.inputs.environment }}"
    
    - name: Set Percy Default Base Build for Percy rerun # Not in use, yet to confirm on this flow
      if: ${{ github.event.inputs.suite == 'rerun' && github.event.inputs.rerun != '' }}
      run: |
        curl -X PATCH https://percy.io/api/v1/projects/70364898/builds/settings \
          -H "Authorization: Token ${{ secrets.PERCY_TEST_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "default_comparison_base": "${{ github.event.inputs.percy_build_number }}"
              }'
      env:
        PERCY_API_TOKEN: ${{ secrets.PERCY_TEST_TOKEN }}

    - name: Run Percy 
      if: ${{ steps.set_percy_default_base_build_for_percy_rerun.outputs.default_comparison_base != '' }}
      # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
      uses: cypress-io/github-action@1b70233146622b69e789ccdd4f9452adc638d25a
      with:
        record: true
        parallel: true
        spec: cypress/e2e/webflow/Percy/percy.cy.js
        command: npx percy exec -- cypress run --spec cypress/e2e/webflow/Percy/percy.cy.js --ci-build-id=$PERCY_BUILD
      env:
        TEST_SUITE: ${{ github.event.inputs.suite }}
        # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Set Base Url from client_payload.
        CYPRESS_BASE_URL: "${{ github.event.inputs.environment }}"
        # Send PR details to Cypress test run
        COMMIT_INFO_MESSAGE: Manual Run of "${{ github.event.inputs.suite }} tests" on "${{ github.event.inputs.environment }}"
        PERCY_TOKEN: ${{ secrets.PERCY_TEST_TOKEN }}
        PERCY_COMMIT: ${{ github.event.inputs.commit_message }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_WEBFLOW_RECORD_KEY }}
        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_WEBFLOW_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        